### ISSUE TITLE
Any update about Vivaldi support?

### ISSUE THREAD

**Issue by Ryah** [evilmanimani/iswitchw#2]
I know it's broken in the current release but was wondering if support would ever return? I use Vivaldi at work and this would be extremely useful for me.

**Comment by mcleodd10** [comment]
Hey, I've actually got it working again; seems to work for me, and I've done a fairly big overhaul to a number of things if you want to test out this branch here:

https://github.com/evilmanimani/iswitchw/tree/overhaul

**Comment by mcleodd10** [comment]
Just pushed an update that fixes browser tab support for Chrome, Vivaldi, and Firefox. Confirmed working in my own tests .
