### ISSUE TITLE
Support for multiple Firefox instances

### ISSUE THREAD

**Issue by rscs** [evilmanimani/iswitchw#3]
I'm a new user to this script.  It is exactly what I've been looking for!  Thank you!

I'm seeing an error in the accv2 script when I have multiple instances of Firefox open.  I typically run the standard Firefox for everyday browsing and the developer Firefox for coding.  They're both always open at the same time. I think the fact that they share a common process name is causing a conflict.

![image](https://user-images.githubusercontent.com/7612149/147032768-30b7dc25-e613-44d3-9c9d-1c4dd23669a3.png)

If I close one of the Firefox instances, the error goes away.

I've confirmed I'm running the 64-bit version of AHK and it's updated to the latest v1.1.33.10 release.

**Comment by mcleodd10** [comment]
I don't use Firefox normally, so not surprising if there's some weirdness with it, I'll check it out when I get a few, thanks for the heads up.

**Comment by mcleodd10** [comment]
Should be working now with the latest update, feel free to reopen if the issue persists.
